### ISSUE TITLE
HoK: javascript indexOf does not work string of numbers

### ISSUE THREAD

**Issue by JSmith-BitFlipper** [mooz/keysnail#156]
For some reason, using plugins.options["hok.hint_keys"] = "1234567890"; causes the evaluations of indexOf in hok to not work. This may be some sort of bug in my firefox or something. This bug causes plugins.options["hok.hide_unmatched_hint"] = true;
plugins.options["hok.unique_only"] = true; 

to not work at all. How can I fix this?

**Comment by mooz** [comment]
It looks like the issue was caused by a change in Firefox's JavaScript engine behavior. I modified HoK to adapt to this change. Plz update HoK and try again.

**Comment by JSmith-BitFlipper** [comment]
It works, thanks for the quick response and update!
