### ISSUE TITLE
Enter key on the firefox address bar does not work.

### ISSUE THREAD

**Issue by tomoyuki28jp** [mooz/keysnail#160]
OSX 10.9.5
firefox 36.0.1
keysnail 2.1.2

**Comment by tomoyuki28jp** [comment]
If I disable keysnail, it works fine. Disabling all keysnail plugins does not solve this problem.

**Comment by tomoyuki28jp** [comment]
keysnail is great and I love this tool so much, so if I can help you anything, please let me know :)

**Comment by debug-ito** [comment]
I can reproduce this bug.

- Xubuntu 14.04 64bit
- Firefox 36.0+build2-0ubuntu0.14.04.4

However, the problem may be a bit different from the one @tomoyuki28jp described.

How to reproduce:

1. Copy a URL somewhere, e.g. in a text editor.
2. Paste the URL to Firefox's address bar.
3. Hit Enter.
4. Nothing happens.

After that, if you type something (like a space) to the address bar and hit enter, then it works. If you type the complete URL in the address bar, hitting Enter works, too.

If you disable keysnail, Enter always works.

**Comment by tomoyuki28jp** [comment]
I've tried the latest version and look like it's been fixed.
Thanks a lot for your great work @mooz!
And thanks for your comment, @debug-ito :)

**Comment by debug-ito** [comment]
Mine is fixed, too. Great work @mooz !!
