### ISSUE TITLE
Trying to bind key for readability - but I'm failing.

### ISSUE THREAD

**Issue by sayash** [mooz/keysnail#164]
I recognize this may be the wrong place to ask for help - but I couldn't find any other way to reach the community. I've been trying to bind a key to call Readability. My code looks like this:
```javascript
ext.add("readability", function() {
  window.baseUrl = 'https://www.readability.com';
  var s = document.createElement('script');
  s.setAttribute('type', 'text/javascript');
  s.setAttribute('charset', 'UTF-8');
  s.setAttribute('src', 'http://www.readability.com/bookmarklet/read.js');
  window.content.document.body.appendChild(s);
}, 'Readability');
```
The 'script' node gets created and appended to the document, but the script doesn't execute, and I don't get a readability-fied document. Further, FireFox complains that `Importing XUL nodes into a content document is deprecated. This functionality may be removed soon.`.

I suspect it's got to do with the `window.baseUrl` and / or `window.content.document.body.appendChild`. Anybody got any tips to point me in the right direction?

**Comment by mooz** [comment]
You should use `content.document` instead of `document` (`document` points Firefox's UI, and it's not HTML but XUL).

Corrected version here (based on the bookmarklet in https://www.readability.com/bookmarklets/):

```javascript
ext.add("readability", function() {
  var window = content.window;
  var document = content.document;
  window.baseUrl = '//www.readability.com';
  window.readabilityToken = '';
  var s = document.createElement('script');
  s.setAttribute('type', 'text/javascript');
  s.setAttribute('charset', 'UTF-8');
  s.setAttribute('src', window.baseUrl + '/bookmarklet/read.js');
  document.documentElement.appendChild(s);
}, 'Readability');
```

**Comment by sayash** [comment]
Ah nice - thank you so much - now I know that content and document are pointing to different things! Thanks so much!
