### ISSUE TITLE
how to quit edit-mode?

### ISSUE THREAD

**Issue by smallst** [mooz/keysnail#165]
i like 'j' 'k' for scrolling page and 'f' for hit a hint. but when under edit mode, i can't find a key to toggle to view mode,i tried "focus to the content" first, but when i focus on a flash area, it doesn't work ,again.  what can i do?

**Comment by mooz** [comment]
"focus to the content" is the most reasonable way to quit edit-mode.

Since flash is not accessible from add-ons including KeySnail, we cannot unfocus flash contents with KeySnail. Consider other softwares like xdotool.
