### ISSUE TITLE
Keysnail broken in Firefox Nightly as of 2015-05-25

### ISSUE THREAD

**Issue by qdot** [mooz/keysnail#166]
Looks like nightly (with e10s turned off) is breaking keysnail again, as of 2015-05-25.

**Comment by unmanbearpig** [comment]
Same thing for me. It never worked with e10s turned on, but now it doesn't work even with e10s turned off.
Does anybody have an idea why it stopped working or how to fix it?

**Comment by qdot** [comment]
Ok, ran keysnail through a debug build, looks like it's choking on JS 1.7 let deprecation. Looks like @mooz has already fixed this on mainline, so I'm hoping I can just rebuild the xpi myself that that'll fix it. Will @mooz close this once they update the xpi in the repo.

**Comment by qdot** [comment]
Just to confirm, built xpi, and removed a let block from my config, and things work fine now.

**Comment by mooz** [comment]
I've updated the xpi. Closing this issue.
Letting user remove let block/expression from their config is cumbersome, though.
