### ISSUE TITLE
submit to mozilla

### ISSUE THREAD

**Issue by rgh36167** [mooz/keysnail#171]
Hi,

one of the next versions of Firefox will completely prevent users from loading extensions not downloaded from Mozilla intentionally eliminating any override or workaround possibilities like installation from local file.

https://wiki.mozilla.org/Addons/Extension_Signing

Having the extension  officially available from Mozilla would be nice anyway and becomes pretty much mandatory because of the singing issue.

**Comment by deadcyclo** [comment]
It already is: https://github.com/mooz/keysnail/issues/168

**Comment by EvaparotangCote** [comment]
@deadcyclo
>It already is: #168 

Do you mean it has already been submitted for request to be signed? (and the "signing"/signature has been [granted](https://github.com/mooz/keysnail/issues/168#issuecomment-133644517)?) That would be correct.

@rgh36167 
>Having the extension officially available from Mozilla would be nice anyway (...).

Regarding KeySnail add-on being officially listed on AMO, that does not seem the case.  
I'm no expert on this signature stuff. I did glance on [Mozilla's wiki page on the topic](https://wiki.mozilla.org/Addons/Extension_Signing) and here's a quote:
>Signing will be done through [addons.mozilla.org (AMO)](http://addons.mozilla.org/) and will be mandatory for all extensions, **regardless of where they are hosted**. (emphasis mine)

So it seems just submitting for signature does not equal submitting for AMO listing. Or am I wrong on that?  
I made a [comment about KeySnail AMO listing in the other thread](https://github.com/mooz/keysnail/issues/168#issuecomment-145087086) as well:
>It seems to at one point have been listed. Quote by /u/mooz from [forums.mozillazine.org](http://forums.mozillazine.org/viewtopic.php?t=1416255):
>>Download from [KeySnail AMO page](https://addons.mozilla.org/en-US/firefox/addon/13118).  
>
>But now the link returns "404 Not found". Also [/u/mooz has a profile on AMO](https://addons.mozilla.org/en-US/firefox/user/mooz/), but KeySnail is not listed among his add-ons.
>Not sure why it's not listed. From the top of my head the only other examples I can think of is [dorando](http://mozilla.dorando.at/readme.html)'s [keyconfig](http://forums.mozillazine.org/viewtopic.php?t=72994) and [HTTPS Everywhere](https://www.eff.org/https-everywhere). I don't currently remember dorando's reason for not listing on AMO and [HTTPS Everywhere has recently made the listing on AMO](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/).
>
>@mooz: Why isn't KeySnail listed on AMO?

**Comment by jeroentbt** [comment]
I'm on Firefox 43.0.1 (KeySnail 2.1.7) and just got the message:

> KeySnail could not be verified for use in Firefox and has been disabled

I'll have to disable `xpinstall.signatures.required` via `about.config` for the time being. More info on signing [here](https://developer.mozilla.org/en-US/Add-ons/Distribution).

**Comment by mkornblum** [comment]
@jeroentbt I had the same thing, I re-installed from the XPI and it works fine now. I think that if you had keysnail installed since before it was Mozilla-signed, the auto-update version is somehow not signed. But reinstalling worked fine for me.

**Comment by jeroentbt** [comment]
@mkornblum Thanks! That did indeed fix things for me too.

I guess this issue can be closed then?
