### ISSUE TITLE
builtin command menu empty

### ISSUE THREAD

**Issue by millwood** [mooz/keysnail#175]
key bindings -> key bindings -> add -> builtin command
a menu of commands pops up but it is empty.
I'm seeing this on 41.0b6 (and earler 41.0 betas).  I don't know when it started. I'll run a regression.
this is what mozgregression claims is the cause:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=e446922ca04d&tochange=fc18eefd9329

**Comment by debug-ito** [comment]
Confirmed on Firefox 41.0 on Xubuntu 14.04.

After updating to 41.0, keysnail first complained about #167.
After fixing #167 manually, it seems to run OK, but all keybindings somehow lost.
I removed my .keysnail.js and all plugins, re-installed keysnail and tried again, but there's still no keybindings.
My keybindings dialog was empty just as @millwood describes above.

**Comment by uhkeller** [comment]
Exactly the same here on Arch Linux after update to Firefox 41.0.

**Comment by Nebukadneza** [comment]
Hi,
and on Debian Testing, after update (vanilla) firefox to 41.0.0 and fixing #167 as shown there.

**Comment by tosmi** [comment]
just a me too. archlinux, firefox 41, keysnail 2.1.6. fixed #167, but keybindings are not working...

**Comment by tomterl** [comment]
I have similar symptoms; The menu isn't completely empty, though: The commands of the HoK-plugin (a keysnail plugin) are present.

**Comment by mooz** [comment]
Fixed in c476cee3ca62c6873c8869b29c7ca092a198a12f. Please wait for a next version.

**Comment by dryice** [comment]
Just a report that I've got this issue on OSX 10.11, Firefox 41, keysnail 2.1.6 too, and the fix in c476cee fixed it. Thanks!

**Comment by millwood** [comment]
Just got 2.1.7 which fixes this but appears to be unsigned again.
