### ISSUE TITLE
How to configure left click + shift to be copy link in firefox

### ISSUE THREAD

**Issue by QiangF** [mooz/keysnail#177]
Hi everyone,
I am wondering if keysnail support binding for the mouse buttons?
I want to copy some links into clipboard manager, the standard right click + copy link is not convenient.
Thank you!

**Comment by EvaparotangCote** [comment]
<sup>tl;dr:</sup>
maybe this:
```js
if(XULBrowserWindow.overLink)
 Components.classes["@mozilla.org/widget/clipboardhelper;1"].
 getService(Components.interfaces.nsIClipboardHelper).copyString(XULBrowserWindow.overLink); 
```  

<sup>full version:</sup>
I once had a shortcut in [dorando](http://mozilla.dorando.at/readme.html)'s [keyconfig](http://forums.mozillazine.org/viewtopic.php?t=72994) set up to do this, it was convenient. But I lost the configuration/profile.  
Tried digging the web, maybe these resources can help, here's what I found:

[dorando](http://mozilla.dorando.at/readme.html) posts:
1. November 13th, 2005: [Copy Email Address shortcut](http://forums.mozillazine.org/viewtopic.php?f=38&t=340552)
2. January 15th, 2008: [remapping spacebar](http://forums.mozillazine.org/viewtopic.php?f=7&t=617309)
3. September 12th, 2008: [keyconfig page 64](http://forums.mozillazine.org/viewtopic.php?p=4451355#p4451355)
4. October 7th, 2008: [keyconfig page 67](http://forums.mozillazine.org/viewtopic.php?p=4677505#p4677505)
5. August 11th, 2010: [keyconfig page 110](http://forums.mozillazine.org/viewtopic.php?p=9739973#p9739973) (same as number 4)
6. July 10th, 2011: [keyconfig page 132](http://forums.mozillazine.org/viewtopic.php?p=11006423#p11006423)
'overLink' seems to be the key argument.
(seems to grab URL from status~~bar~~panel-text (no?).)

http://bbs.kafan.cn/thread-1474099-1-1.html seems to be "[escaped](https://www.google.com/?q=bookmarklet+escaped)" version of number 5, quote:
>user_pref("keyconfig.main.xxx_key1_Copy_Link_Link", "control shift][C][][if(XULBrowserWindow.overLink)\nComponents.classes[\"@mozilla.org/widget/clipboardhelper;1\"].\ngetService(Components.interfaces.nsIClipboardHelper).copyString(XULBrowserWindow.\n\noverLink); ][");  


>user_pref("keyconfig.main.xxx_key1_Copy_Text_Link", "control shift][C][][if(XULBrowserWindow.overLink)\nfor (var i = 0, links = content.document.links, l = links.length ; i < l; i++)\nif(links.href == XULBrowserWindow.overLink) {\nComponents.classes[\"@mozilla.org/widget/clipboardhelper;1\"]\n.getService(Components.interfaces.nsIClipboardHelper)\n.copyString(links.text + \" - \" + links.href);\n\nbreak;\n}  ][");

Similar resources:
https://sites.google.com/site/bookmarks576/Home/addons/keyconfig
[Gist - FireGestures Code](https://gist.github.com/dearmark/886cd7dc61aba4a78a6a)
2012-8-7: http://g.mozest.com/viewthread.php?action=printable&tid=41991

Other resources:
2012-10-22: http://g.mozest.com/viewthread.php?tid=42536&page=1#pid294455
2012-10-24: http://g.mozest.com/viewthread.php?tid=42557&page=1#pid294558

Largely unrelated, but came up when searching 'overLink':
https://gist.github.com/Griever/300255
https://addons.mozilla.org/en-us/firefox/addon/url-tooltips/

More copy link stuff:
https://github.com/gomita/firegestures/search?utf8=%E2%9C%93&q=copy+link&type=Code
https://github.com/gomita/firegestures/search?utf8=%E2%9C%93&q=*hovered*&type=Code
https://github.com/gomita/firegestures/blob/7a3c2e422577b34c6d5f31fc3a1bcaac250da4b9/chrome/content/firegestures/browser.js#L534
http://forums.mozillazine.org/search.php?keywords=overLink&t=72994&sf=msgonly
Mar 25 '12: [Firefox Extension that copies HTML link to current web page to clipboard and not just the URL](https://stackoverflow.com/questions/9854044/firefox-extension-that-copies-html-link-to-current-web-page-to-clipboard-and-not/9862893#9862893)
October 20th, 2014: [Need help in Firegesture script](http://forums.mozillazine.org/viewtopic.php?f=7&t=2881799)

**Comment by QiangF** [comment]
Now I set the binding to do other things with my window manager. 
Thank you!

**Comment by EvaparotangCote** [comment]
Cool! Great to hear!
Could you maybe put up a [Gist](https://gist.github.com/) showing how you're using it, and what "binding[s] to do other things" you've got? Could be interesting to see.

**Comment by QiangF** [comment]
In openbox, when you switch window with Alt+tab, you need hit many tabs to get the window you want, so I bind shift+right click to 
client-list-combined-menu
which shows all windows and is selectable with the mouse.
