### ISSUE TITLE
keysnail cannot use in firefox 41.0

### ISSUE THREAD

**Issue by smallst** [mooz/keysnail#178]
after update firefox to 41.0.  issue #167  appears.when i corrected js file,i found all bindingkeys cannot work.and as #175 command menu is empty. what can i do? wait for new version?

**Comment by millwood** [comment]
keybindings work for others.  possibly you fumbled the "correction" of the js file.  You need to get the {} right but also clean up any let expressions - replaced by let statements.

You might post the code of one of your bindings.

**Comment by smallst** [comment]
@millwood  i rename the .keysnail.js file and create a new one.paste old one to it and works.i really don't know what happend.but thank you, i can use keysnail again.  :)
