### ISSUE TITLE
Wiki tip section seems to be wrong, K2emacs

### ISSUE THREAD

**Issue by jtamagnan** [mooz/keysnail#190]
There seems to be an error on the wiki that sent me for a loop. The line that caused problem is in the tip section of the wiki in the part that talks about K2emacs it has the line:
``` javascript
...
ext.exec("edit_text", arg);
...
```
Which never worked for me. Instead this line worked for me:
``` javascript
...
ext.exec("edit_text", arg, ev);
...
```

**Comment by mooz** [comment]
Great. Thanks!

https://github.com/mooz/keysnail/wiki/Tips/_compare/3ba1b3d7298f363d65c52f205567357ec9d14035...3782a13357d53ac645c0cd0df0a80fa32c16d2eb
