### ISSUE TITLE
KKK stopped working for me

### ISSUE THREAD

**Issue by jgeerds** [mooz/keysnail#216]
It seems like the `KKK` plugin stopped working for me since the latest Firefox update (`49.0`). Keys like `j` or `k` are handled by GitHub. Is anyone else experiencing the same issue or able to confirm that this is working as it should?

```
plugins.options["kkk.sites"] = [
    "^https?://([0-9a-zA-Z]+\\.)?github\\.com/",
    "^https?://([0-9a-zA-Z]+\\.)?google\\.com/",
];
```

Do you need any further information? Unfortunately, I don't know how to debug keysnail or KKK

**Comment by kccai** [comment]
I am using `Firefox Nightly 52.0a1 (2016-09-20) (64-bit)` with the multi-process feature disabled. `KKK` works normal for me on both GitHub and Google.

**Comment by jgeerds** [comment]
Weird... it works for me again. Closing this.

Thanks kccai!
